name: Deploy Streamlit App to EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-24.04

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 3: Deploy to EC2
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@<EC2_PUBLIC_IP> << 'EOF'
          # Navigate to home directory
          cd /home/ubuntu

          # Define project folder name
          PROJECT_NAME="Visionary_AI"

          # Clone repository if not already cloned
          if [ ! -d "$PROJECT_NAME" ]; then
             git clone https://github.com/Arjun9271/Visionary_AI_Empowering_the_visually_impaired.git "$PROJECT_NAME"
          fi
          cd "$PROJECT_NAME"

          # Pull latest changes
          git pull

          # Create and activate virtual environment
          python3 -m venv venv
          source venv/bin/activate

          # Install dependencies with pip3
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

          # Run Streamlit app
          nohup ./venv/bin/streamlit run app.py > streamlit.log 2>&1 &
          EOF
